import type { AppUser } from "@/lib/permissions";

export const defaultUsers: AppUser[] = [
  {
    id: "yves",
    firstName: "Yves",
    lastName: "Moreel",
    fullName: "Yves Moreel",
    email: "yves@zeverrock.be",
    initials: "YM",
    kind: "admin",
    modules: [],
    tasks: [],
    days: null,
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "degi",
    firstName: "Degi",
    lastName: "",
    fullName: "Degi",
    email: "degi@zeverrock.be",
    initials: "DE",
    kind: "team",
    modules: ["documenten", "social-media", "medewerkers"],
    tasks: ["opbouw", "afbouw"],
    days: "both",
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "an",
    firstName: "An",
    lastName: "Janssens",
    fullName: "An Janssens",
    email: "an@zeverrock.be",
    initials: "AJ",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "saturday",
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
];
