import type { AppUser } from "@/lib/permissions";
import { daysFromFestivalByDay, sanitizeFestivalByDay } from "@/lib/staff-tasks";

type SeedUser = Omit<AppUser, "tshirtSizeSaturday" | "festivalByDay"> & {
  festivalByDay?: AppUser["festivalByDay"];
};

function withSaturdaySize(user: SeedUser): AppUser {
  const festivalByDay = sanitizeFestivalByDay(user.festivalByDay, user.days, user.tasks);
  const days = daysFromFestivalByDay(festivalByDay);

  return {
    ...user,
    festivalByDay,
    days,
    tshirtSizeSaturday: days === "both" && user.tshirtConfirmed ? user.tshirtSize : null,
  };
}

const seedUsers: SeedUser[] = [
  {
    id: "yves",
    firstName: "Yves",
    lastName: "Moreel",
    fullName: "Yves Moreel",
    email: "yves@zeverrock.be",
    initials: "YM",
    kind: "admin",
    modules: [],
    tasks: [],
    days: null,
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "degi",
    firstName: "Degi",
    lastName: "",
    fullName: "Degi",
    email: "degi@zeverrock.be",
    initials: "DE",
    kind: "team",
    modules: ["documenten", "social-media", "medewerkers"],
    tasks: ["opbouw", "afbouw"],
    days: "both",
    opbouwDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    afbouwDays: ["sunday", "monday", "tuesday"],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "lien",
    firstName: "Lien",
    lastName: "Peeters",
    fullName: "Lien Peeters",
    email: "lien@zeverrock.be",
    initials: "LP",
    kind: "team",
    modules: ["social-media", "media"],
    tasks: [],
    days: null,
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "tom",
    firstName: "Tom",
    lastName: "De Smet",
    fullName: "Tom De Smet",
    email: "tom@zeverrock.be",
    initials: "TD",
    kind: "team",
    modules: ["sponsoring", "documenten"],
    tasks: ["opbouw"],
    days: null,
    opbouwDays: ["thursday", "friday"],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "an",
    firstName: "An",
    lastName: "Janssens",
    fullName: "An Janssens",
    email: "an@zeverrock.be",
    initials: "AJ",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "kasper",
    firstName: "Kasper",
    lastName: "Willems",
    fullName: "Kasper Willems",
    email: "kasper@zeverrock.be",
    initials: "KW",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "elise",
    firstName: "Elise",
    lastName: "Vermeulen",
    fullName: "Elise Vermeulen",
    email: "elise@zeverrock.be",
    initials: "EV",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "wout",
    firstName: "Wout",
    lastName: "Claes",
    fullName: "Wout Claes",
    email: "wout@zeverrock.be",
    initials: "WC",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "marieke",
    firstName: "Marieke",
    lastName: "De Clercq",
    fullName: "Marieke De Clercq",
    email: "marieke@zeverrock.be",
    initials: "MD",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "dries",
    firstName: "Dries",
    lastName: "Van Damme",
    fullName: "Dries Van Damme",
    email: "dries@zeverrock.be",
    initials: "DV",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: null,
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "niels",
    firstName: "Niels",
    lastName: "Coppens",
    fullName: "Niels Coppens",
    email: "niels@zeverrock.be",
    initials: "NC",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "sofie",
    firstName: "Sofie",
    lastName: "Maes",
    fullName: "Sofie Maes",
    email: "sofie@zeverrock.be",
    initials: "SM",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "bram",
    firstName: "Bram",
    lastName: "Goossens",
    fullName: "Bram Goossens",
    email: "bram@zeverrock.be",
    initials: "BG",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "laura",
    firstName: "Laura",
    lastName: "De Wilde",
    fullName: "Laura De Wilde",
    email: "laura@zeverrock.be",
    initials: "LD",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "pieter",
    firstName: "Pieter",
    lastName: "Lambrecht",
    fullName: "Pieter Lambrecht",
    email: "pieter@zeverrock.be",
    initials: "PL",
    kind: "staff",
    modules: [],
    tasks: ["opbouw"],
    days: null,
    opbouwDays: ["monday", "tuesday", "wednesday"],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "jolien",
    firstName: "Jolien",
    lastName: "Baert",
    fullName: "Jolien Baert",
    email: "jolien@zeverrock.be",
    initials: "JB",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "toog-a"],
    days: "saturday",
    opbouwDays: ["thursday", "friday"],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "koen",
    firstName: "Koen",
    lastName: "Van Acker",
    fullName: "Koen Van Acker",
    email: "koen@zeverrock.be",
    initials: "KV",
    kind: "staff",
    modules: [],
    tasks: ["afbouw"],
    days: null,
    opbouwDays: [],
    afbouwDays: ["sunday", "monday", "tuesday"],
    tshirtSizeLastYear: "XXL",
    tshirtSize: "XXL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "hanne",
    firstName: "Hanne",
    lastName: "Smets",
    fullName: "Hanne Smets",
    email: "hanne@zeverrock.be",
    initials: "HS",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "afbouw"],
    days: null,
    opbouwDays: ["friday"],
    afbouwDays: ["sunday"],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "milo",
    firstName: "Milo",
    lastName: "De Smet",
    fullName: "Milo De Smet",
    email: "milo@zeverrock.be",
    initials: "MS",
    kind: "staff",
    modules: [],
    tasks: ["toog-a", "runner"],
    days: "both",
    festivalByDay: { friday: "toog-a", saturday: "runner" },
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "leen",
    firstName: "Leen",
    lastName: "Wouters",
    fullName: "Leen Wouters",
    email: "leen@zeverrock.be",
    initials: "LW",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "stijn",
    firstName: "Stijn",
    lastName: "Vermeersch",
    fullName: "Stijn Vermeersch",
    email: "stijn@zeverrock.be",
    initials: "SV",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "afbouw"],
    days: null,
    opbouwDays: ["monday", "tuesday", "wednesday", "thursday"],
    afbouwDays: ["sunday", "monday"],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "fien",
    firstName: "Fien",
    lastName: "Claeys",
    fullName: "Fien Claeys",
    email: "fien@zeverrock.be",
    initials: "FC",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen", "toog-b"],
    days: "both",
    festivalByDay: { friday: "kassawagen", saturday: "toog-b" },
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "ruben",
    firstName: "Ruben",
    lastName: "Verstraeten",
    fullName: "Ruben Verstraeten",
    email: "ruben@zeverrock.be",
    initials: "RV",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "emma",
    firstName: "Emma",
    lastName: "Vandenberghe",
    fullName: "Emma Vandenberghe",
    email: "emma@zeverrock.be",
    initials: "EV",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "jelle",
    firstName: "Jelle",
    lastName: "Moens",
    fullName: "Jelle Moens",
    email: "jelle@zeverrock.be",
    initials: "JM",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "lotte",
    firstName: "Lotte",
    lastName: "Snoeck",
    fullName: "Lotte Snoeck",
    email: "lotte@zeverrock.be",
    initials: "LS",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "arne",
    firstName: "Arne",
    lastName: "De Pauw",
    fullName: "Arne De Pauw",
    email: "arne@zeverrock.be",
    initials: "AD",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "kato",
    firstName: "Kato",
    lastName: "Vercruysse",
    fullName: "Kato Vercruysse",
    email: "kato@zeverrock.be",
    initials: "KV",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "matthias",
    firstName: "Matthias",
    lastName: "Declercq",
    fullName: "Matthias Declercq",
    email: "matthias@zeverrock.be",
    initials: "MD",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "noor",
    firstName: "Noor",
    lastName: "Van den Abeele",
    fullName: "Noor Van den Abeele",
    email: "noor@zeverrock.be",
    initials: "NV",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "robbe",
    firstName: "Robbe",
    lastName: "Dewaele",
    fullName: "Robbe Dewaele",
    email: "robbe@zeverrock.be",
    initials: "RD",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: null,
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "femke",
    firstName: "Femke",
    lastName: "Coppejans",
    fullName: "Femke Coppejans",
    email: "femke@zeverrock.be",
    initials: "FC",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "senne",
    firstName: "Senne",
    lastName: "Dierickx",
    fullName: "Senne Dierickx",
    email: "senne@zeverrock.be",
    initials: "SD",
    kind: "staff",
    modules: [],
    tasks: ["toog-a", "toog-b"],
    days: "both",
    festivalByDay: { friday: "toog-a", saturday: "toog-b" },
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "amber",
    firstName: "Amber",
    lastName: "Van Hoecke",
    fullName: "Amber Van Hoecke",
    email: "amber@zeverrock.be",
    initials: "AV",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen", "toog-a"],
    days: "both",
    festivalByDay: { friday: "kassawagen", saturday: "toog-a" },
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "tuur",
    firstName: "Tuur",
    lastName: "Rombaut",
    fullName: "Tuur Rombaut",
    email: "tuur@zeverrock.be",
    initials: "TR",
    kind: "staff",
    modules: [],
    tasks: ["opbouw"],
    days: null,
    opbouwDays: ["monday", "tuesday", "wednesday"],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "celine",
    firstName: "Celine",
    lastName: "De Backer",
    fullName: "Celine De Backer",
    email: "celine@zeverrock.be",
    initials: "CD",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "toog-b"],
    days: "saturday",
    opbouwDays: ["thursday", "friday"],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "ward",
    firstName: "Ward",
    lastName: "Callens",
    fullName: "Ward Callens",
    email: "ward@zeverrock.be",
    initials: "WC",
    kind: "staff",
    modules: [],
    tasks: ["afbouw"],
    days: null,
    opbouwDays: [],
    afbouwDays: ["sunday", "monday", "tuesday"],
    tshirtSizeLastYear: "XXL",
    tshirtSize: "XXL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "ines",
    firstName: "Ines",
    lastName: "Vanhee",
    fullName: "Ines Vanhee",
    email: "ines@zeverrock.be",
    initials: "IV",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "afbouw"],
    days: null,
    opbouwDays: ["friday"],
    afbouwDays: ["sunday"],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "lennert",
    firstName: "Lennert",
    lastName: "Bossuyt",
    fullName: "Lennert Bossuyt",
    email: "lennert@zeverrock.be",
    initials: "LB",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "saar",
    firstName: "Saar",
    lastName: "Debruyne",
    fullName: "Saar Debruyne",
    email: "saar@zeverrock.be",
    initials: "SD",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "gilles",
    firstName: "Gilles",
    lastName: "Van Hecke",
    fullName: "Gilles Van Hecke",
    email: "gilles@zeverrock.be",
    initials: "GV",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "merel",
    firstName: "Merel",
    lastName: "Stevens",
    fullName: "Merel Stevens",
    email: "merel@zeverrock.be",
    initials: "MS",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "toog-a"],
    days: "both",
    opbouwDays: ["monday", "tuesday"],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
];

export const defaultUsers: AppUser[] = seedUsers.map(withSaturdaySize);
