import type { AppUser } from "@/lib/permissions";

export const defaultUsers: AppUser[] = [
  {
    id: "yves",
    firstName: "Yves",
    lastName: "Moreel",
    fullName: "Yves Moreel",
    email: "yves@zeverrock.be",
    initials: "YM",
    kind: "admin",
    modules: [],
    tasks: [],
    days: null,
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "degi",
    firstName: "Degi",
    lastName: "",
    fullName: "Degi",
    email: "degi@zeverrock.be",
    initials: "DE",
    kind: "team",
    modules: ["documenten", "social-media", "medewerkers"],
    tasks: ["opbouw", "afbouw"],
    days: "both",
    opbouwDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    afbouwDays: ["sunday", "monday", "tuesday"],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "lien",
    firstName: "Lien",
    lastName: "Peeters",
    fullName: "Lien Peeters",
    email: "lien@zeverrock.be",
    initials: "LP",
    kind: "team",
    modules: ["social-media", "media"],
    tasks: [],
    days: null,
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "tom",
    firstName: "Tom",
    lastName: "De Smet",
    fullName: "Tom De Smet",
    email: "tom@zeverrock.be",
    initials: "TD",
    kind: "team",
    modules: ["sponsoring", "documenten"],
    tasks: ["opbouw"],
    days: null,
    opbouwDays: ["thursday", "friday"],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "an",
    firstName: "An",
    lastName: "Janssens",
    fullName: "An Janssens",
    email: "an@zeverrock.be",
    initials: "AJ",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "kasper",
    firstName: "Kasper",
    lastName: "Willems",
    fullName: "Kasper Willems",
    email: "kasper@zeverrock.be",
    initials: "KW",
    kind: "staff",
    modules: [],
    tasks: ["toog-a"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "elise",
    firstName: "Elise",
    lastName: "Vermeulen",
    fullName: "Elise Vermeulen",
    email: "elise@zeverrock.be",
    initials: "EV",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "wout",
    firstName: "Wout",
    lastName: "Claes",
    fullName: "Wout Claes",
    email: "wout@zeverrock.be",
    initials: "WC",
    kind: "staff",
    modules: [],
    tasks: ["toog-b"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "marieke",
    firstName: "Marieke",
    lastName: "De Clercq",
    fullName: "Marieke De Clercq",
    email: "marieke@zeverrock.be",
    initials: "MD",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "dries",
    firstName: "Dries",
    lastName: "Van Damme",
    fullName: "Dries Van Damme",
    email: "dries@zeverrock.be",
    initials: "DV",
    kind: "staff",
    modules: [],
    tasks: ["kassawagen"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: null,
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "niels",
    firstName: "Niels",
    lastName: "Coppens",
    fullName: "Niels Coppens",
    email: "niels@zeverrock.be",
    initials: "NC",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "both",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "sofie",
    firstName: "Sofie",
    lastName: "Maes",
    fullName: "Sofie Maes",
    email: "sofie@zeverrock.be",
    initials: "SM",
    kind: "staff",
    modules: [],
    tasks: ["runner"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "bram",
    firstName: "Bram",
    lastName: "Goossens",
    fullName: "Bram Goossens",
    email: "bram@zeverrock.be",
    initials: "BG",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "friday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "XL",
    tshirtSize: "XL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "laura",
    firstName: "Laura",
    lastName: "De Wilde",
    fullName: "Laura De Wilde",
    email: "laura@zeverrock.be",
    initials: "LD",
    kind: "staff",
    modules: [],
    tasks: ["ingang"],
    days: "saturday",
    opbouwDays: [],
    afbouwDays: [],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "pieter",
    firstName: "Pieter",
    lastName: "Lambrecht",
    fullName: "Pieter Lambrecht",
    email: "pieter@zeverrock.be",
    initials: "PL",
    kind: "staff",
    modules: [],
    tasks: ["opbouw"],
    days: null,
    opbouwDays: ["monday", "tuesday", "wednesday"],
    afbouwDays: [],
    tshirtSizeLastYear: "L",
    tshirtSize: "L",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "jolien",
    firstName: "Jolien",
    lastName: "Baert",
    fullName: "Jolien Baert",
    email: "jolien@zeverrock.be",
    initials: "JB",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "toog-a"],
    days: "saturday",
    opbouwDays: ["thursday", "friday"],
    afbouwDays: [],
    tshirtSizeLastYear: "M",
    tshirtSize: "M",
    tshirtConfirmed: false,
    active: true,
  },
  {
    id: "koen",
    firstName: "Koen",
    lastName: "Van Acker",
    fullName: "Koen Van Acker",
    email: "koen@zeverrock.be",
    initials: "KV",
    kind: "staff",
    modules: [],
    tasks: ["afbouw"],
    days: null,
    opbouwDays: [],
    afbouwDays: ["sunday", "monday", "tuesday"],
    tshirtSizeLastYear: "XXL",
    tshirtSize: "XXL",
    tshirtConfirmed: true,
    active: true,
  },
  {
    id: "hanne",
    firstName: "Hanne",
    lastName: "Smets",
    fullName: "Hanne Smets",
    email: "hanne@zeverrock.be",
    initials: "HS",
    kind: "staff",
    modules: [],
    tasks: ["opbouw", "afbouw"],
    days: null,
    opbouwDays: ["friday"],
    afbouwDays: ["sunday"],
    tshirtSizeLastYear: "S",
    tshirtSize: "S",
    tshirtConfirmed: true,
    active: true,
  },
];
